apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helpers.releaseName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "helpers.name" . }}
    chart: {{ template "helpers.chartRelease" . }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "helpers.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "helpers.name" . }}
        chart: {{ template "helpers.chartRelease" . }}
        release: {{ .Release.Name | quote }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: walle-webservice
          image: {{ .Values.image }}
          args:
            {{- range .Values.dockerCmdOverride }}
            - {{ . | quote }}
            {{- end}}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 1
              memory: 2Gi
          imagePullPolicy: "IfNotPresent"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 20
            periodSeconds: 30
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: COURSIER_CACHE
              value: {{ .Values.coursierCache.location }}
          volumeMounts:
            - name: config-volume
              readOnly: true
              mountPath: /application.properties
              subPath: application.properties
          {{- if not .Values.aws.irsaRole }}
            - name: aws-creds
              mountPath: "/.aws"
              readOnly: true
            {{- end }}
            - name: dataservices-creds
              mountPath: "/.llama-serve"
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "helpers.releaseName" . }}
      {{- if not .Values.aws.irsaRole }}
        - name: aws-creds
          secret:
            secretName: addps-aws-secret
        {{- end }}
        - name: dataservices-creds
          secret:
            secretName: {{ .Values.dataserviceCredentials }}