apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "helpers.releaseName" . }}
  labels:
    app: {{ template "helpers.name" . }}
    chart: {{ template "helpers.chartRelease" . }}
    release: {{ .Release.Name | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "helpers.releaseName" . }}
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90